<?php

namespace Tests\Feature;


use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Event;
use Tests\TestCase;
use DateTime;


class StudentControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Event::fake();
    }

    public function testCreateStudent()
    {

        $user = factory(User::class)->create(['role' => 1]);

        $response = $this->actingAs($user)
            ->post('/admin/students', [
                'fullname' => 'Pham Ngoc Anh',
                'email' => 'ngocanhphamkk2@gmail.com',
                'birthday' => date_format(new DateTime('26-03-2000'), 'Y-m-d'),
                'gender' => 1,
                'phone_number' => '0336330633',
                'address' => '159 Tieu Hoang Street',
                'faculty_id' => 1,
                'avatar' => UploadedFile::fake()->image('avatarTest.jpg')
            ]);
        $response->assertRedirect('/admin/students');
    }


}
